application: go-tilenkranjc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.app
  login: required
  
- url: /add
  script: main.app
  login: required
  
- url: /del/.*
  script: main.app
  login: required
  
- url: /edit/.*
  script: main.app
  login: required
  
- url: /static
  static_dir: static
  login: required

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest
